"""
generate_scenario_files.py
============================
Generates one .rou.xml and one .sumocfg per (scenario, seed) combination
in the manifest, from the demand rates declared in scenario_manifest.py.

This never touches the frozen network (intersection.nod.xml,
.edg.xml, .con.xml, .tll.xml, .net.xml) or the original
intersection.rou.xml, it only writes new files into
sumo/routes/scenarios/ and sumo/config/scenarios/. Route IDs and edges
are copied verbatim from the original frozen route file's structure, only
the vehsPerHour values and the random seed differ per generated file.

Run directly:
    python -m ml.training.generate_scenario_files
"""

import os

from ml.training.config import TrainingConfig
from ml.training.scenario_manifest import SCENARIOS, Scenario

# Route ID -> (edges) copied verbatim from the frozen intersection.rou.xml.
# Kept here, not re-parsed from the XML file, so this script has no
# dependency on being able to parse the frozen route file's exact
# formatting, only on the route topology, which is part of the frozen
# network's design and will not change independently of it.
_ROUTE_EDGES = {
    "route_N_S": "N_in C_out_S",
    "route_N_E": "N_in C_out_E",
    "route_N_W": "N_in C_out_W",
    "route_S_N": "S_in C_out_N",
    "route_S_E": "S_in C_out_E",
    "route_S_W": "S_in C_out_W",
    "route_E_W": "E_in C_out_W",
    "route_E_N": "E_in C_out_N",
    "route_E_S": "E_in C_out_S",
    "route_W_E": "W_in C_out_E",
    "route_W_N": "W_in C_out_N",
    "route_W_S": "W_in C_out_S",
}

_SIMULATION_END_SECONDS = 600
_STEP_LENGTH_SECONDS = 0.05


def _run_id(scenario: Scenario, seed: int) -> str:
    return "{}_seed{}".format(scenario.name, seed)


def _build_route_xml(scenario: Scenario) -> str:
    """
    Build a .rou.xml file's contents for a scenario: the same vType and
    route definitions as the frozen route file, with flow vehsPerHour
    values taken from the scenario's demand profile.
    """
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!--",
        "    Generated by ml/training/generate_scenario_files.py for",
        "    scenario '{}'. {}".format(scenario.name, scenario.description),
        "    Do not hand edit, regenerate from scenario_manifest.py instead.",
        "-->",
        "<routes>",
        '    <vType id="car" accel="2.6" decel="4.5" sigma="0.5" length="5.0"',
        '           minGap="2.5" maxSpeed="13.89" guiShape="passenger"/>',
        "",
    ]

    for route_id, edges in _ROUTE_EDGES.items():
        lines.append('    <route id="{}" edges="{}"/>'.format(route_id, edges))

    lines.append("")

    for route_id in _ROUTE_EDGES:
        rate = scenario.flow_rates.get(route_id, 0.0)
        if rate <= 0.0:
            continue
        flow_id = "flow_{}".format(route_id)
        lines.append(
            '    <flow id="{}" type="car" route="{}" begin="0" '
            'end="{}" vehsPerHour="{}"/>'.format(
                flow_id, route_id, _SIMULATION_END_SECONDS, rate
            )
        )

    lines.append("</routes>")
    return "\n".join(lines) + "\n"


def _build_sumocfg_xml(scenario: Scenario, seed: int, route_filename: str) -> str:
    """
    Build a .sumocfg file's contents for one (scenario, seed) run,
    pointing at the frozen network, this scenario's generated route
    file, and a fixed random seed for reproducibility.
    """
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!--\n"
        "    Generated by ml/training/generate_scenario_files.py for\n"
        "    scenario '{scenario_name}', seed {seed}.\n"
        "    Points at the frozen network, never modifies it.\n"
        "-->\n"
        "<configuration>\n"
        "    <input>\n"
        '        <net-file value="../../network/intersection.net.xml"/>\n'
        '        <route-files value="../../routes/scenarios/{route_filename}"/>\n'
        "    </input>\n"
        "    <time>\n"
        '        <begin value="0"/>\n'
        '        <end value="{end}"/>\n'
        '        <step-length value="{step_length}"/>\n'
        "    </time>\n"
        "    <random>\n"
        '        <seed value="{seed}"/>\n'
        "    </random>\n"
        "</configuration>\n"
    ).format(
        scenario_name=scenario.name,
        seed=seed,
        route_filename=route_filename,
        end=_SIMULATION_END_SECONDS,
        step_length=_STEP_LENGTH_SECONDS,
    )


def generate_all() -> None:
    """
    Generate one .rou.xml per scenario (shared across all seeds of that
    scenario, since demand rates don't depend on the seed, only SUMO's
    internal random vehicle-arrival realization does) and one .sumocfg
    per (scenario, seed) combination.
    """
    TrainingConfig.ensure_output_directories()

    for scenario in SCENARIOS:
        route_filename = "{}.rou.xml".format(scenario.name)
        route_path = os.path.join(TrainingConfig.SCENARIO_ROUTES_DIR, route_filename)
        with open(route_path, "w", encoding="utf-8") as f:
            f.write(_build_route_xml(scenario))

        for seed in scenario.seeds:
            run_id = _run_id(scenario, seed)
            sumocfg_path = os.path.join(
                TrainingConfig.SCENARIO_CONFIGS_DIR, "{}.sumocfg".format(run_id)
            )
            with open(sumocfg_path, "w", encoding="utf-8") as f:
                f.write(_build_sumocfg_xml(scenario, seed, route_filename))

    print(
        "Generated {} route file(s) and {} sumocfg file(s).".format(
            len(SCENARIOS),
            sum(len(s.seeds) for s in SCENARIOS),
        )
    )


if __name__ == "__main__":
    generate_all()